### ISSUE TITLE
Deciding if a method is accessible from the target interface in the case that the method is declared in the same type as the source method

### ISSUE THREAD

**Issue by khatchad** [khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring#77]
In the case that:

1. the member whose access is in question and the source method are declared in the same type,
2. the member's declaring type is accessible from target, and
3. the member's declaring type and the target type are different.

The question that arises is if the target type can access the **particular** member given that the target type can access the member's declaring type. Suppose the member is an instance method.  We need to make sure that the destination interface is able to access this instance method. However, we also need to make sure that the run time target of the method invocation remains the same after the refactoring. 

So, in this case, it's not enough to judge accessibility but we also need to judge the preservation of semantics. I don't think that `edu.cuny.citytech.defaultrefactoring.core.refactorings.MigrateSkeletalImplementationToInterfaceRefactoringProcessor.canBeAccessedFrom(IMethod, IMember, IType, ITypeHierarchy)` should be responsible for this. 

This is also a problem for the Pull Up refactoring, however, there is a bug in Eclipse (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=487278). They don't need to deal with this because they disallow any member in the type that declares the source method. 

I suppose there's a case in a very complex hierarchy that not having the method in the source method's declared type could also change semantics, e.g., if you pull up the method over the original run time target method. As such, there may be some other code in the Pull Up refactoring that takes care of this case. We may discover that later.

In the meantime, I'll disable the failing tests due to this problem (see below).

-- Error Log from JUnit --
Class: edu.cuny.citytech.defaultrefactoring.ui.tests.MigrateSkeletalImplementationToInterfaceRefactoringTest
Method: testMethodThatCallsAnotherMethod10
Actual: null
Expected: null
Stack Trace:
junit.framework.AssertionFailedError: Precondition was supposed to pass.
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.TestCase.assertTrue(TestCase.java:192)
	at edu.cuny.citytech.refactoring.common.tests.RefactoringTest.helperPass(RefactoringTest.java:172)
	at edu.cuny.citytech.defaultrefactoring.ui.tests.MigrateSkeletalImplementationToInterfaceRefactoringTest.testMethodThatCallsAnotherMethod10(MigrateSkeletalImplementationToInterfaceRefactoringTest.java:554)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.extensions.TestSetup.run(TestSetup.java:27)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:62)
	at org.eclipse.pde.internal.junit.runtime.PlatformUITestHarness$1.run(PlatformUITestHarness.java:47)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(NonUIThreadTestApplication.java:54)
	at org.eclipse.pde.internal.junit.runtime.UITestApplication.runApp(UITestApplication.java:47)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(NonUIThreadTestApplication.java:48)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

**Comment by khatchad** [comment]
> I suppose there's a case in a very complex hierarchy that not having the method in the source method's declared type could also change semantics, e.g., if you pull up the method over the original run time target method. As such, there may be some other code in the Pull Up refactoring that takes care of this case. We may discover that later.

There's no such code that I could find.

**Comment by khatchad** [comment]
This is actually more general. The called method can be inherited by the source type (not just declared directly in it).

**Comment by khatchad** [comment]
(In reply to comment #0)
> ...
> 
> So, in this case, it's not enough to judge accessibility but we also need to judge the preservation of semantics. I don't think that `edu.cuny.citytech.defaultrefactoring.core.refactorings.MigrateSkeletalImplementationToInterfaceRefactoringProcessor.canBeAccessedFrom(IMethod, IMember, IType, ITypeHierarchy)` should be responsible for this.

It should be done in `edu.cuny.citytech.defaultrefactoring.core.refactorings.MigrateSkeletalImplementationToInterfaceRefactoringProcessor.checkAccessedMethods(IMethod, Optional<IProgressMonitor>, ITypeHierarchy)`.

**Comment by khatchad** [comment]
(In reply to comment #2)
> > I suppose there's a case in a very complex hierarchy that not having the
> method in the source method's declared type could also change semantics, e.g.,
> if you pull up the method over the original run time target method. As such,
> there may be some other code in the Pull Up refactoring that takes care of this
> case. We may discover that later.
> 
> There's no such code that I could find.

Actually, I think it has something to do with `org.eclipse.jdt.internal.corext.refactoring.structure.PullUpRefactoringProcessor.getSkippedSuperTypes(IProgressMonitor)`.

**Comment by khatchad** [comment]
(In reply to comment #5)
> (In reply to comment #2)
> > > I suppose there's a case in a very complex hierarchy that not having the
> > method in the source method's declared type could also change semantics, e.g.,
> > if you pull up the method over the original run time target method. As such,
> > there may be some other code in the Pull Up refactoring that takes care of
> this
> > case. We may discover that later.
> >
> > There's no such code that I could find.
> 
> Actually, I think it has something to do with
> `org.eclipse.jdt.internal.corext.refactoring.structure.PullUpRefactoringProcessor.getSkippedSuperTypes(IProgressMonitor)`.

But, this issue is about deciding if a method is accessible from the target interface in the case that the method is declared in the same type as the source method (i.e., the declaring type). So, skipped types don't really come into play here because we won't be "skipping" the declaring type. Should open a new issue for this problem.

**Comment by khatchad** [comment]
Opened #121.
